### ISSUE TITLE
SnowyKITTI  datasets

### ISSUE THREAD

**Issue by wanghangege** [alvariseppanen/4DenoiseNet#10]
Thank you for your excellent work, but I have a problem, can you help? The SnowyKITTIs you provided is so huge that even though I have the right internet access, it is still difficult for  researchers in mainland China to download it （Always download interrupted）. Can you split the data into several sets, or try to publish it on another platform, like one drive or Baidu cloud drive? Thank you.

**Comment by wyw-dlut** [comment]
不会翻墙是吧

**Comment by icy-obelisk** [comment]
[baidu netdisk link](https://pan.baidu.com/s/1d4l1kLJuxcMMAHfahagGpw?pwd=754h)

Enjoy.

**Comment by icy-obelisk** [comment]
> Thank you for your excellent work, but I have a problem, can you help? The SnowyKITTIs you provided is so huge that even though I have the right internet access, it is still difficult for researchers in mainland China to download it （Always download interrupted）. Can you split the data into several sets, or try to publish it on another platform, like one drive or Baidu cloud drive? Thank you.

[baidu netdisk link](https://pan.baidu.com/s/1d4l1kLJuxcMMAHfahagGpw?pwd=754h)

Enjoy.

**Comment by wanghangege** [comment]
thank you very much.
