### ISSUE TITLE
The question of test

### ISSUE THREAD

**Issue by cchester25** [alvariseppanen/4DenoiseNet#3]
Hello, after reading your paper, I think it is very good, and I want to repeat the effect. I tried to use infer.py and the data in the folder-toy_snowyKITTI to test the network, but there are some problems in the operation process, I don't quite understand.That is 
"INTERFACE:
dataset /home/pf/open_source_code/4DenoiseNet-main/toy_snowyKITTI/dataset/
log /home/pf/open_source_code/4DenoiseNet_predict/
model /home/pf/open_source_code/4DenoiseNet-main/logs/2022-9-22-20:56/
Uncertainty False
Monte Carlo Sampling 30
infering test
Opening arch config file from /home/pf/open_source_code/4DenoiseNet-main/logs/2022-9-22-20:56/
Opening data config file from /home/pf/open_source_code/4DenoiseNet-main/logs/2022-9-22-20:56/
train 05
train 06
train 07
train 16
train 21
valid 08
valid 09
valid 11
valid 12
valid 13
valid 14
test 00
test 01
test 02
test 03
test 04
model folder exists! Using model from /home/pf/open_source_code/4DenoiseNet-main/logs/2022-9-22-20:56/
Sequences folder exists! Using sequences from /home/pf/open_source_code/4DenoiseNet-main/toy_snowyKITTI/dataset/sequences
parsing seq 00
parsing seq 01
parsing seq 02
parsing seq 03
parsing seq 04
Using 0 scans from sequences [0, 1, 2, 3, 4]
Traceback (most recent call last):
  File "infer.py", line 145, in <module>
    user = User(ARCH, DATA, FLAGS.dataset, FLAGS.log, FLAGS.model,FLAGS.split,FLAGS.monte_carlo)
  File "../../tasks/semantic/modules/user.py", line 51, in __init__
    shuffle_train=False)
  File "../..//tasks/semantic/dataset/kitti/parser.py", line 463, in __init__
    assert len(self.testloader) > 0
AssertionError"
Looking forward to your reply.

**Comment by alvariseppanen** [comment]
Hi,

The problem seems to be that it is trying to infer sequences 00-05, and the toy dataset includes sequence 22.
So, I modified the /4DenoiseNet/logs/2022-9-22-20:56/data_cfg.yaml file to infer sequence 22. You can pull the repo and try again to see if it works now.

Best regards,
Alvari

**Comment by cchester25** [comment]
Hello, this problem has been solved, but due to the PyTorch version, some properties are not compatible, may I ask which version of PyTorch should I use to run this algorithm?
