### ISSUE TITLE
The question of view

### ISSUE THREAD

**Issue by cchester25** [alvariseppanen/4DenoiseNet#4]
I upgraded the PyTorch version to 1.12.0, so I successfully tested the model, but when I used **snow_visualize. py** to view the lidar points in toy_snowyKITTI, error is "could not find config/semantic-kitti-mos.yaml."
the reason is  in README.md, ### Visualize:   python3 snow_visualize.py -d root/toy_snowyKITTI/dataset/ **-dc** root/networks/train/tasks/semantic/config/labels/snowy-kitti.yaml -p /your/predictions/folder/ -s 22
**-dc** should be **-c**.  then i successfully viewed the effect of denoising.
I just came into contact with the research on noise reduction in bad weather. Your research surprised me. I hope that one day I can propose a good algorithm and open source it .

**Comment by alvariseppanen** [comment]
Thank you, README.md is now fixed
